# Generated by Django 5.1.7 on 2025-04-24 09:39

from django.db import migrations, models

def set_default_values(apps, schema_editor):
    Guest = apps.get_model('hotel', 'Guest')
    for guest in Guest.objects.all():
        guest.country = 'US'  # Default country
        guest.id_type = 'passport'  # Default ID type
        guest.save()

class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='country',
            field=models.CharField(choices=[('PK', 'Pakistan'), ('US', 'United States'), ('GB', 'United Kingdom'), ('CA', 'Canada'), ('AU', 'Australia'), ('IN', 'India'), ('AE', 'United Arab Emirates'), ('SA', 'Saudi Arabia')], default='US', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guest',
            name='id_type',
            field=models.CharField(choices=[('passport', 'Passport'), ('cnic', 'CNIC'), ('driving_license', 'Driving License')], max_length=50),
        ),
        migrations.AlterField(
            model_name='guest',
            name='id_number',
            field=models.CharField(max_length=50),
        ),
        migrations.RunPython(set_default_values),
    ]
