# Generated by Django 5.2 on 2025-04-25 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_room_image_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
