# Generated by Django 5.2 on 2025-04-25 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_guest_vehicle_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#4285F4', max_length=20)),
                ('secondary_color', models.CharField(default='#34A853', max_length=20)),
                ('danger_color', models.CharField(default='#EA4335', max_length=20)),
                ('warning_color', models.CharField(default='#FBBC05', max_length=20)),
                ('sidebar_color', models.CharField(default='#343a40', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
