# Generated by Django 5.1.7 on 2025-04-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_themesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='id_document',
            field=models.ImageField(blank=True, help_text='Upload ID document (CNIC/Passport)', null=True, upload_to='guest_ids/'),
        ),
    ]
