# Generated by Django 5.1.7 on 2025-04-26 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_guest_id_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('receptionist', 'Receptionist')], default='receptionist', max_length=20),
        ),
    ]
