# Generated by Django 5.1.7 on 2025-05-06 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_remove_booking_id_alter_booking_booking_id'),
    ]

    operations = [
    ]
